# Generated by Django 3.2.25 on 2024-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentapp', '0004_rename_replydate_complaint_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=5000)),
                ('positive', models.CharField(max_length=50)),
                ('negative', models.CharField(max_length=50)),
                ('nuetral', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
